# Generated by Django 4.1 on 2023-10-13 21:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('color', models.CharField(blank=True, max_length=8, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('modified_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'user',
                'ordering': ['id'],
            },
        ),
    ]
